build: fix build errors
- Update Visual Studio build tools from v142 to v143

Assignment 1:
- Fix compiler error C3052 [1]. There was no compiler errors when I was
  still working on this assignment, no idea why it occurred on Visual
  Studio 2022.

- Remove x64 build configuration as they doesn't seem to work.  The lab
  solution doesn't have a x64 build configuration too [2]

- Add Assignment Handout and General Class Feedback PDFs, retrieved from
  [3]. They are informational and I should have included them.

Assignment 2:
- Copy compiler error C3052 fix from Assignment 1
- Update CUDA Toolkit version from 10.2 to 12.1
- Add Assignment Handout PDF, retrieved from [3]

[1]: https://learn.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c3052?view=msvc-170
[2]: https://github.com/mondus/com4521/tree/Lab03_sln
[3]: https://github.com/Vlados09/cuda-nbody-simulation

Signed-off-by: unknown <engzerjun@gmail.com>